package br.ufrn.imd.modelo;

public enum GameState {
    CLIQUE,
    POSICIONAR_CORVETA,
    POSICIONAR_SUBMARINO,
    POSICIONAR_FRAGATA,
    POSICIONAR_DESTROYER,

    SELECIONAR_ALVOS_CORVETA,
    SELECIONAR_ALVOS_SUBMARINO,
    SELECIONAR_ALVOS_FRAGATA,
    SELECIONAR_ALVOS_DESTROYER,

    SELECIONAR_ALVOS,

    ENDGAME
}
